version: "3"
services:
  front:
    image: itay016/basta_front:latest

    # env_file: .prod.env
#    volumes:
      # - ./static:/app/.next/static/
#      - ./db/sqliteDB:/app/db/sqliteDB
    restart: always
    command: >
      sh -c "npm run start"
    ports:
      - "3000:3000"
    networks:
      - common-network

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/basta/static
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - front
    networks:
      - common-network

networks:
  common-network:
    external: true

volumes:
  front:
    external: true
  certbot:
  nginx_secrets:
